### ISSUE TITLE
timthumbs-v3.txt' is not a file (OptParseValidator::Error)

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan-v3#35]
I get ```timthumbs-v3.txt' is not a file (OptParseValidator::Error)``` when installing from ```gem install wpscan```.

```
Ryans-MacBook-Pro:wpscan ryandewhurst$ wpscan
-bash: wpscan: command not found
```

```
Ryans-MacBook-Pro:wpscan ryandewhurst$ gem install wpscan
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: i18n-0.9.1.gem (100%)
Successfully installed i18n-0.9.1
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.4.gem (100%)
Successfully installed tzinfo-1.2.4
Fetching: activesupport-5.1.4.gem (100%)
Successfully installed activesupport-5.1.4
Fetching: opt_parse_validator-0.0.13.11.gem (100%)
Successfully installed opt_parse_validator-0.0.13.11
Fetching: cms_scanner-0.0.37.12.gem (100%)
Successfully installed cms_scanner-0.0.37.12
Fetching: wpscan-3.0.6.gem (100%)
Successfully installed wpscan-3.0.6
8 gems installed
```

```
Ryans-MacBook-Pro:wpscan ryandewhurst$ wpscan -u http://example.com/
/Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:40:in `check_file': '/Users/ryandewhurst/.wpscan/db/timthumbs-v3.txt' is not a file (OptParseValidator::Error)
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:26:in `block in validate'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:24:in `each'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:24:in `validate'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:44:in `add_option'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `block in add'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `each'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `add'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/cms_scanner-0.0.37.12/lib/cms_scanner/controllers.rb:29:in `<<'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:11:in `block in <top (required)>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/cms_scanner-0.0.37.12/lib/cms_scanner.rb:92:in `initialize'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:5:in `new'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:5:in `<top (required)>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/wpscan:23:in `load'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/wpscan:23:in `<main>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/ruby_executable_hooks:15:in `<main>'
```

```
Ryans-MacBook-Pro:wpscan ryandewhurst$ cd ~/.wpscan/db/
-bash: cd: /Users/ryandewhurst/.wpscan/db/: No such file or directory
```

```
Ryans-MacBook-Pro:wpscan ryandewhurst$ wpscan
/Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:40:in `check_file': '/Users/ryandewhurst/.wpscan/db/timthumbs-v3.txt' is not a file (OptParseValidator::Error)
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:26:in `block in validate'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:24:in `each'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:24:in `validate'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:44:in `add_option'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `block in add'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `each'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `add'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/cms_scanner-0.0.37.12/lib/cms_scanner/controllers.rb:29:in `<<'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:11:in `block in <top (required)>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/cms_scanner-0.0.37.12/lib/cms_scanner.rb:92:in `initialize'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:5:in `new'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:5:in `<top (required)>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/wpscan:23:in `load'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/wpscan:23:in `<main>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by erwanlr** [comment]
That's weird, it should have updated the DB when a file is missing

please run ```wpscan --update``` and try again

**Comment by erwanlr** [comment]
Ohhh, I know why ;P

Btw, -u is for --update now, the url is --url

**Comment by ethicalhack3r** [comment]
Same error when using ```--url``` :)

```
$ wpscan --url http://example.com/
/Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:40:in `check_file': '/Users/ryandewhurst/.wpscan/db/timthumbs-v3.txt' is not a file (OptParseValidator::Error)
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:26:in `block in validate'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:24:in `each'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator/opts/path.rb:24:in `validate'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:44:in `add_option'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `block in add'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `each'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/opt_parse_validator-0.0.13.11/lib/opt_parse_validator.rb:32:in `add'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/cms_scanner-0.0.37.12/lib/cms_scanner/controllers.rb:29:in `<<'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:11:in `block in <top (required)>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/cms_scanner-0.0.37.12/lib/cms_scanner.rb:92:in `initialize'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:5:in `new'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/gems/wpscan-3.0.6/bin/wpscan:5:in `<top (required)>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/wpscan:23:in `load'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/wpscan:23:in `<main>'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ryandewhurst/.rvm/gems/ruby-2.4.2@wpscan/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by erwanlr** [comment]
I know ;p

It's because the default option values are now validated, so the existence of the db file is checked.

Will have to update the OptParseValidator first

**Comment by erwanlr** [comment]
3.0.7 fixing that released
