### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by dot-m00se** [wpscanteam/wpscan-v3#37]
Getting the following error when using the "--format json" switch.

ᐅ **docker run --rm wpscanteam/wpscan-v3 --format json --url www.example.com**
```
     /usr/local/bundle/gems/yajl-ruby-1.3.1/lib/yajl/json_gem/parsing.rb:15:in 
     `rescue in parse': parse error: after array element, I expect ',' or ']' 
     (JSON::ParserError) "@erwan_lr"     "@_FireFart_"   ],   "sponsored_by": "Sucur (right here) ------^
	from /usr/local/bundle/gems/yajl-ruby-1.3.1/lib/yajl/json_gem/parsing.rb:12:in `parse'
	from /usr/local/bundle/gems/cms_scanner-0.0.38.1/app/formatters/json.rb:8:in `beautify'
	from /usr/local/bundle/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:116:in `run'
	from /usr/local/bundle/gems/wpscan-3.0.7/bin/wpscan:14:in `block in <top (required)>'
	from /usr/local/bundle/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:92:in `initialize'
	from /usr/local/bundle/gems/wpscan-3.0.7/bin/wpscan:5:in `new'
	from /usr/local/bundle/gems/wpscan-3.0.7/bin/wpscan:5:in `<top (required)>'
	from /usr/local/bundle/bin/wpscan:23:in `load'
	from /usr/local/bundle/bin/wpscan:23:in `<main>'
```

**Comment by dot-m00se** [comment]
Missing "," in the banner.erb  file at line 7.

```
~/.rvm/gems/ruby-2.4.2/gems/wpscan-3.0.7/app/views/json/core ᐅ cat banner.erb
"banner": {
"description": "WordPress Security Scanner by the WPScan Team",
  "version": <%= WPScan::VERSION.to_json %>,
  "authors": [
    "@_WPScan_",
    "@ethicalhack3r",
    "@erwan_lr"
    "@_FireFart_"
  ],
  "sponsored_by": "Sucuri - https://sucuri.net"
},
```

Seems to be sorted out now thanks.
