### ISSUE TITLE
redirect follow ?

### ISSUE THREAD

**Issue by d4op** [wpscanteam/wpscan-v3#38]
Why isnt my wpscan 3.0.8 automatically following the redirect ? 
there is no switch anymore --follow-redirect ?!
and i dont want to abort or ignore the redirect. i want to follow lol

some idea ?

Scan Aborted: The URL supplied redirects to http://xxx.info/blog/. Use the --ignore-main-redirect option to ignore the redirection and scan the target.
Trace: /var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.1/app/controllers/core.rb:47:in `check_target_availability'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.1/app/controllers/core.rb:21:in `before_scan'
/var/lib/gems/2.3.0/gems/wpscan-3.0.8/app/controllers/core.rb:53:in `before_scan'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.1/lib/cms_scanner/controllers.rb:41:in `each'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.1/lib/cms_scanner/controllers.rb:41:in `run'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:101:in `run'
/var/lib/gems/2.3.0/gems/wpscan-3.0.8/bin/wpscan:14:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:92:in `initialize'
/var/lib/gems/2.3.0/gems/wpscan-3.0.8/bin/wpscan:5:in `new'
/var/lib/gems/2.3.0/gems/wpscan-3.0.8/bin/wpscan:5:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

**Comment by erwanlr** [comment]
Then supply the correct URL directly to the --url option ;p

**Comment by d4op** [comment]
Why isnt v3 following like v2.9 ? or why is the switch --follow-redirection removed ?
it was really handy.

how to fix this issue ?

**Comment by d4op** [comment]
if this message appear wouldnt it be logical, if the wpscan follows the redirection ? otherwhise the --ignore-main-redirect switch doesnt make sense to me.

please add again 
--follow-redirection               

or just let it redirect automatically, if the other flag isnt set.

**Comment by erwanlr** [comment]
If the redirected URL is in scope (i.e. in a subdirectory or subdomain or https/http side of the entered URL), it should be followed already.

So, if you are supplying http://example.com and the redirect is http://example.com/blog/ or https://blog.example.com, then no error should occur. If you are in such case, there is something wrong somewhere, and please send us the url you are scanning (at team at wpscan dot org) so we can have a look.

If you are entering http://example.com and the redirect is http://google.com then you entered the wrong url to scan (or the blog redirects you to something else and can be ignored with the --ignore-main-redirect, I've seen such behaviour in some blogs, caused by anti-scanner plugins or example)

**Comment by d4op** [comment]
even if i enter xxx.com without http:// or https:// it abored the scan because it redirects to https://xxx.com
thats shitty :p 

will wildcard work ? --scope *

**Comment by erwanlr** [comment]
Random WP blog with redirect like you describe:

```curl -I http://wagbrag.com```
<img width="277" alt="screen shot 2017-11-23 at 11 38 39" src="https://user-images.githubusercontent.com/1668843/33171048-a6969efa-d042-11e7-9bed-2259547031d9.png">

```wpscan --detection-mode passive --url wagbrag.com```
<img width="477" alt="screen shot 2017-11-23 at 11 39 43" src="https://user-images.githubusercontent.com/1668843/33171072-c3626fdc-d042-11e7-873d-8af4b8d52b32.png">

**Comment by d4op** [comment]
okay i see nvm. was some bug on my side.

now subdomains etc working fine. 

will you add widecard ? like * to accept all redirections ?
nvm of which sub or new domain it is ?

otherwise this will be a feature request.
