### ISSUE TITLE
Scan Aborted: QueryParameter is not allowed as a Dynamic Finder

### ISSUE THREAD

**Issue by zachsis** [wpscanteam/wpscan-v3#39]
**Error output:**
```
[me@localhost wpscan-v3]$ wpscan -v --url "https://www.mysite.com/blog"

[ banner truncated ] 

Scan Aborted: QueryParameter is not allowed as a Dynamic Finder
Trace: /home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/lib/wpscan/db/dynamic_finders.rb:103:in `version_finder_super_class'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/lib/wpscan/db/dynamic_finders.rb:87:in `block (2 levels) in create_versions_finders'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/lib/wpscan/db/dynamic_finders.rb:84:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/lib/wpscan/db/dynamic_finders.rb:84:in `block in create_versions_finders'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/lib/wpscan/db/dynamic_finders.rb:78:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/lib/wpscan/db/dynamic_finders.rb:78:in `create_versions_finders'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/controllers/enumeration.rb:9:in `before_scan'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/controllers.rb:41:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/controllers.rb:41:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:101:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/bin/wpscan:14:in `block in <top (required)>'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:92:in `initialize'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/bin/wpscan:5:in `new'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/bin/wpscan:5:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/bin/wpscan:23:in `load'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/bin/wpscan:23:in `<main>'
```

**ruby version:**
```
[me@localhost wpscan-v3]$ rvm list
 * ruby-2.1.10 [ x86_64 ]
   ruby-2.2.2 [ x86_64 ]
=> ruby-2.3.3 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

**gem list:**
```
[me@localhost wpscan-v3]$ gem list

*** LOCAL GEMS ***

activesupport (5.1.4)
addressable (2.5.2)
ast (2.3.0)
bigdecimal (default: 1.2.8)
bundler (1.16.0)
bundler-unload (1.0.2)
cms_scanner (0.0.38.1)
concurrent-ruby (1.0.5)
coveralls (0.8.21)
crack (0.4.3)
did_you_mean (1.0.0)
diff-lcs (1.3)
docile (1.1.5)
ethon (0.11.0)
executable-hooks (1.3.2)
ffi (1.9.18)
gem-wrappers (1.4.0)
hashdiff (0.3.7)
i18n (0.9.1)
io-console (default: 0.4.5)
json (2.1.0, default: 1.8.3)
mini_portile2 (2.3.0)
minitest (5.10.3, 5.8.5)
net-telnet (0.1.1)
nokogiri (1.8.1)
opt_parse_validator (0.0.14.1)
parallel (1.12.0)
parser (2.4.0.2)
power_assert (0.2.6)
powerpack (0.1.1)
psych (default: 2.1.0)
public_suffix (3.0.1)
rainbow (2.2.2)
rake (12.3.0, 10.4.2)
rdoc (default: 4.2.1)
rspec (3.7.0)
rspec-core (3.7.0)
rspec-expectations (3.7.0)
rspec-its (1.2.0)
rspec-mocks (3.7.0)
rspec-support (3.7.0)
rubocop (0.51.0)
ruby-progressbar (1.9.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
safe_yaml (1.0.4)
simplecov (0.14.1)
simplecov-html (0.10.2)
term-ansicolor (1.6.0)
test-unit (3.1.5)
thor (0.19.4)
thread_safe (0.3.6)
tins (1.15.1)
typhoeus (1.3.0)
tzinfo (1.2.4)
unicode-display_width (1.3.0)
webmock (3.1.1)
wpscan (3.0.8)
yajl-ruby (1.3.1)
```

**OS Version:**
```
[me@localhost wpscan-v3]$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
```

**kernel version**
```
Linux localhost.localdomain 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**bundle install && rake install Output**
```
me@localhost wpscan-v3]$ bundle install && rake install
Fetching gem metadata from https://rubygems.org/...............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Fetching rake 12.3.0
Installing rake 12.3.0
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 0.9.1
Installing i18n 0.9.1
Fetching minitest 5.10.3
Installing minitest 5.10.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.4
Installing tzinfo 1.2.4
Fetching activesupport 5.1.4
Installing activesupport 5.1.4
Fetching public_suffix 3.0.1
Installing public_suffix 3.0.1
Fetching addressable 2.5.2
Installing addressable 2.5.2
Fetching ast 2.3.0
Installing ast 2.3.0
Using bundler 1.16.0
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.1
Installing nokogiri 1.8.1 with native extensions
Fetching opt_parse_validator 0.0.14.1
Installing opt_parse_validator 0.0.14.1
Fetching ruby-progressbar 1.9.0
Installing ruby-progressbar 1.9.0
Fetching ffi 1.9.18
Installing ffi 1.9.18 with native extensions
Fetching ethon 0.11.0
Installing ethon 0.11.0
Fetching typhoeus 1.3.0
Installing typhoeus 1.3.0
Fetching yajl-ruby 1.3.1
Installing yajl-ruby 1.3.1 with native extensions
Fetching cms_scanner 0.0.38.1
Installing cms_scanner 0.0.38.1
Fetching json 2.1.0
Installing json 2.1.0 with native extensions
Fetching docile 1.1.5
Installing docile 1.1.5
Fetching simplecov-html 0.10.2
Installing simplecov-html 0.10.2
Fetching simplecov 0.14.1
Installing simplecov 0.14.1
Fetching tins 1.15.1
Installing tins 1.15.1
Fetching term-ansicolor 1.6.0
Installing term-ansicolor 1.6.0
Fetching thor 0.19.4
Installing thor 0.19.4
Fetching coveralls 0.8.21
Installing coveralls 0.8.21
Fetching safe_yaml 1.0.4
Installing safe_yaml 1.0.4
Fetching crack 0.4.3
Installing crack 0.4.3
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching hashdiff 0.3.7
Installing hashdiff 0.3.7
Fetching parallel 1.12.0
Installing parallel 1.12.0
Fetching parser 2.4.0.2
Installing parser 2.4.0.2
Fetching powerpack 0.1.1
Installing powerpack 0.1.1
Fetching rainbow 2.2.2
Installing rainbow 2.2.2 with native extensions
Fetching rspec-support 3.7.0
Installing rspec-support 3.7.0
Fetching rspec-core 3.7.0
Installing rspec-core 3.7.0
Fetching rspec-expectations 3.7.0
Installing rspec-expectations 3.7.0
Fetching rspec-mocks 3.7.0
Installing rspec-mocks 3.7.0
Fetching rspec 3.7.0
Installing rspec 3.7.0
Fetching rspec-its 1.2.0
Installing rspec-its 1.2.0
Fetching unicode-display_width 1.3.0
Installing unicode-display_width 1.3.0
Fetching rubocop 0.51.0
Installing rubocop 0.51.0
Fetching webmock 3.1.1
Installing webmock 3.1.1
Using wpscan 3.0.8 from source at `.`
Bundle complete! 9 Gemfile dependencies, 46 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
/home/me/.rvm/rubies/ruby-2.3.3/bin/ruby -I/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/rspec-core-3.7.0/lib:/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/rspec-support-3.7.0/lib /home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/rspec-core-3.7.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
.....**.*..........................................................................*..***...***...............*.....................................................................*....*..................*....*....*.*................*.*..**.....***.......*...*....**...........*.......................................*...*...........................................****....................*...*.*....*...........*...*.*....*.........*..........................................................................................................................*...............................................................................*..

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) WPScan::Controller::BruteForce#passwords 
     # Temporarily skipped with xit
     # ./spec/app/controllers/brute_force_spec.rb:44

  2) WPScan::Controller::BruteForce#output_error 
     # Temporarily skipped with xit
     # ./spec/app/controllers/brute_force_spec.rb:48

  3) WPScan::Controller::BruteForce#brute_force 
     # Temporarily skipped with xit
     # ./spec/app/controllers/brute_force_spec.rb:60

  4) WPScan::Finders::InterestingFindings::EmergencyPwdResetScript#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/emergency_pwd_reset_script_spec.rb:10

  5) WPScan::Finders::InterestingFindings::MuPlugins#passive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/mu_plugins_spec.rb:10

  6) WPScan::Finders::InterestingFindings::MuPlugins#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/mu_plugins_spec.rb:14

  7) WPScan::Finders::InterestingFindings::Multisite#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/multisite_spec.rb:10

  8) WPScan::Finders::InterestingFindings::Registration#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/registration_spec.rb:10

  9) WPScan::Finders::InterestingFindings::TmmDbMigrate#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/tmm_db_migrate_spec.rb:10

  10) WPScan::Finders::InterestingFindings::UploadDirectoryListing#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/interesting_findings/upload_direcrory_listing_spec.rb:11

  11) WPScan::Finders::Medias::AttachmentBruteForcing#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/medias/attachment_brute_forcing_spec.rb:10

  12) WPScan::Finders::Plugins::KnownLocations#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/plugins/known_locations_spec.rb:10

  13) WPScan::Finders::Plugins::UrlsInHomepage#passive 
     # Temporarily skipped with xit
     # ./spec/app/finders/plugins/urls_in_homepage_spec.rb:25

  14) WPScan::Finders::Themes::KnownLocations#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/themes/known_locations_spec.rb:10

  15) WPScan::Finders::Themes::UrlsInHomepage#passive 
     # Temporarily skipped with xit
     # ./spec/app/finders/themes/urls_in_homepage_spec.rb:18

  16) WPScan::Finders::Timthumbs::KnownLocations#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/timthumbs/known_locations_spec.rb:10

  17) WPScan::Finders::Users::AuthorIdBruteForcing#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/users/author_id_brute_forcing_spec.rb:10

  18) WPScan::Finders::Users::AuthorPosts#passive 
     # Temporarily skipped with xit
     # ./spec/app/finders/users/author_posts_spec.rb:10

  19) WPScan::Finders::Users::LoginErrorMessages#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/users/login_error_messages_spec.rb:10

  20) WPScan::Finders::Users::OembedApi#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/users/oembed_api_spec.rb:10

  21) WPScan::Finders::Users::WpJsonApi#aggressive 
     # Temporarily skipped with xit
     # ./spec/app/finders/users/wp_json_api_spec.rb:10

  22) WPScan::Finders::WpVersion::AtomGenerator 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/atom_generator_spec.rb:9

  23) WPScan::Finders::WpVersion::HomepageStylesheetNumbers 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/homepage_stylesheet_numbers_spec.rb:9

  24) WPScan::Finders::WpVersion::InstallStylesheetNumbers 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/install_stylesheet_numbers_spec.rb:9

  25) WPScan::Finders::WpVersion::RDFGenerator 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/rdf_generator_spec.rb:9

  26) WPScan::Finders::WpVersion::RSSGenerator 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/rss_generator_spec.rb:9

  27) WPScan::Finders::WpVersion::UniqueFingerprinting 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/unique_fingerprinting_spec.rb:9

  28) WPScan::Finders::WpVersion::UpgradeStylesheetNumbers 
     # Temporarily skipped with xit
     # ./spec/app/finders/wp_version/upgrade_stylesheet_numbers_spec.rb:9

  29) WPScan::InterestingFinding behaves like WPScan::References references when references provided as array 
     # Temporarily skipped with xit
     # ./spec/shared_examples/references.rb:46

  30) WPScan::Theme#vulnerabilities 
     # Temporarily skipped with xit
     # ./spec/app/models/theme_spec.rb:90

  31) WPScan::Theme#parent_themes 
     # Temporarily skipped with xit
     # ./spec/app/models/theme_spec.rb:137

  32) WPScan::WpItem#readme_url 
     # Temporarily skipped with xit
     # ./spec/app/models/wp_item_spec.rb:104

  33) WPScan::WpItem#changelog_url 
     # Temporarily skipped with xit
     # ./spec/app/models/wp_item_spec.rb:108

  34) WPScan::WpItem#directory_listing? 
     # Temporarily skipped with xit
     # ./spec/app/models/wp_item_spec.rb:112

  35) WPScan::WpItem#error_log? 
     # Temporarily skipped with xit
     # ./spec/app/models/wp_item_spec.rb:116

  36) App::Views when JSON behaves like App::Views::Enumeration behaves like App::Views::Enumeration::Users users when users found outputs the expected string
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/users.rb:18

  37) App::Views when JSON behaves like App::Views::Enumeration behaves like App::Views::Enumeration::Themes themes when themes found 
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/themes.rb:16

  38) App::Views when JSON behaves like App::Views::Enumeration behaves like App::Views::Enumeration::Plugins plugins when plugins found 
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/plugins.rb:16

  39) App::Views when JSON behaves like App::Views::Enumeration behaves like App::Views::Enumeration::ConfigBackups config_backups when backups found 
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/config_backups.rb:16

  40) App::Views when CliNoColour behaves like App::Views::Enumeration behaves like App::Views::Enumeration::Users users when users found outputs the expected string
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/users.rb:18

  41) App::Views when CliNoColour behaves like App::Views::Enumeration behaves like App::Views::Enumeration::Themes themes when themes found 
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/themes.rb:16

  42) App::Views when CliNoColour behaves like App::Views::Enumeration behaves like App::Views::Enumeration::Plugins plugins when plugins found 
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/plugins.rb:16

  43) App::Views when CliNoColour behaves like App::Views::Enumeration behaves like App::Views::Enumeration::ConfigBackups config_backups when backups found 
     # Temporarily skipped with xit
     # ./spec/shared_examples/views/enumeration/config_backups.rb:16

  44) WPScan::DB::DynamicPluginFinders.maybe_create_module 
     # Temporarily skipped with xit
     # ./spec/lib/db/dynamic_plugin_finders_spec.rb:44

  45) WPScan::Finders::Finder::WpVersion::SmartURLChecker 
     # Temporarily skipped with xit
     # ./spec/lib/finders/finder/wp_version/smart_url_checker_spec.rb:4

  46) WPScan::Vulnerability behaves like WPScan::References references when references provided as array 
     # Temporarily skipped with xit
     # ./spec/shared_examples/references.rb:46


Finished in 1.96 seconds (files took 1.27 seconds to load)
639 examples, 0 failures, 46 pending

Coverage report generated for RSpec to /home/me/wpscan-v3/coverage. 1500 / 1794 LOC (83.61%) covered.
Running RuboCop...
Inspecting 240 files
................................................................................................................................................................................................................................................

240 files inspected, no offenses detected
wpscan 3.0.8 built to pkg/wpscan-3.0.8.gem.
wpscan (3.0.8) installed.
```

**Comment by erwanlr** [comment]
How did you install wpscan, via gem install or build from this repository ?

**Comment by zachsis** [comment]
Built from this repository

**Comment by erwanlr** [comment]
Then you will have to rebuild due to yesterday's changes :)

**Comment by zachsis** [comment]
hehe k. one moment.

**Comment by zachsis** [comment]
fixed! thx
