### ISSUE TITLE
--format=json crash [JSON::ParserError]

### ISSUE THREAD

**Issue by Ondrysak** [wpscanteam/wpscan-v3#61]
running 
`wpscan --stealthy --url=http://www.rybydojezirka.cz/`
works totally fine, but when using json format
`wpscan --stealthy --format=json --url=http://www.rybydojezirka.cz/`

following happens

```
Traceback (most recent call last):
	11: from /home/ujo/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	10: from /home/ujo/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	 9: from /home/ujo/.rvm/gems/ruby-2.5.0/bin/wpscan:23:in `<main>'
	 8: from /home/ujo/.rvm/gems/ruby-2.5.0/bin/wpscan:23:in `load'
	 7: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/wpscan-3.2.1/bin/wpscan:5:in `<top (required)>'
	 6: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/wpscan-3.2.1/bin/wpscan:5:in `new'
	 5: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/cms_scanner-0.0.39.1/lib/cms_scanner.rb:92:in `initialize'
	 4: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/wpscan-3.2.1/bin/wpscan:15:in `block in <top (required)>'
	 3: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/cms_scanner-0.0.39.1/lib/cms_scanner.rb:116:in `run'
	 2: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/cms_scanner-0.0.39.1/app/formatters/json.rb:8:in `beautify'
	 1: from /home/ujo/.rvm/gems/ruby-2.5.0/gems/yajl-ruby-1.3.1/lib/yajl/json_gem/parsing.rb:11:in `parse'
/home/ujo/.rvm/gems/ruby-2.5.0/gems/yajl-ruby-1.3.1/lib/yajl/json_gem/parsing.rb:15:in `rescue in parse': lexical error: invalid bytes in UTF8 string. (JSON::ParserError)
          ness or portfolio website, it�s fully responsive design read
                     (right here) ------^

```

**Comment by erwanlr** [comment]
Thanks for the report, this has been fixed in the CMSScanner gem. So all you have to do is run ```gem update cms_scanner``` then run wpscan as usual :)
